### ISSUE TITLE
Integration Token Credential ID

### ISSUE THREAD

**Issue by idokaplan** [jenkinsci/slack-plugin#272]
Hi,

I cannot choose "Credential ID".
The list is empty, but there are credentials that are configured.

Can you please advise?
Thanks!
Ido

**Comment by vinhtvu2** [comment]
Are they configured as "Secret Text" in the "Kind" field?

**Comment by fredpalmer** [comment]
@vinhtvu2 Open dev tools - I found that I couldn't get the credentials plugin to _truly_ add the credentials via the build configuration page due to a `Mixed Content` issue:

https://issues.jenkins-ci.org/browse/JENKINS-35150

<img width="1068" alt="developer_tools_-_https___builds_artistgrowth_com_job_ag-nexus-webtest-build_configure" src="https://cloud.githubusercontent.com/assets/32422/23316216/1d35cc3c-fa8f-11e6-987e-d3c7bfdcf6a1.png">


I think you can get around it by adding the credentials directly: `<your-build-server>/credentials/store/system/domain/_/newCredentials`

**Comment by jblaine** [comment]
This doesn't work for me either.

I tried version 2.2.

I configured a "Secret text" credential in my Jenkins folder (not from the job config page) as we do for all manner of other credentials and types just fine. When configuring a job there to try to use Slack, the secret text credential does not show as a choice in the drop-down, effectively making this plugin fully inoperable for us :(

**Comment by dsoprea** [comment]
Bump. I'm having this issue, too.

**Comment by dsoprea** [comment]
It looks like there's an issue with creating it as a non-admin user but then not being able to see it because you're a non-admin. It's a Jenkinsism.

**Comment by eagletmt** [comment]
I also ran into this issue. I've created a PR to fix this #315

**Comment by Edwin-van-der-Klaauw** [comment]
This is a serious bug because I have to give all users system admin access rights to the entire Jenkins environment or else non-admin users saving one of the projects will silently break the link with Slack notifications leaving new build/test failures unnotified to the teams. This bug makes the whole plug-in useless. There seems to be something fundamentally wrong with access rights; How can you have NO READ access but do have WRITE (clear) access? Please fix!

**Comment by haidaraM** [comment]
No one seems to maintain this plugin anymore :confused:

**Comment by timja** [comment]
fix released in 2.4

**Comment by rishabhjain05** [comment]
Hi, I am facing an issue with the credential's dropdown, it only shows "none" no matter how many times I have added the secret key. I also tried to reinstall the Slack notification plugin and also restart the Jenkins twice. But still facing the same issue.

**Comment by timja** [comment]
> Hi, I am facing an issue with the credential's dropdown, it only shows "none" no matter how many times I have added the secret key. I also tried to reinstall the Slack notification plugin and also restart the Jenkins twice. But still facing the same issue.

the scope needs to be set to global and of the "Secret text" type.

Please create a new issue and post a screenshot if it's still an issue after the above
